### ISSUE TITLE
Théme noir automatique et non supporté

### ISSUE THREAD

**Issue by jdauphant** [betagouv/pass-sport#80]
## Problème

J'ai automatiquement le théme noir sur mon ordi (c'est la config par défaut de mon navigateur ) :
![image](https://github.com/betagouv/pass-sport/assets/1238254/07795340-8406-4e42-b2a1-d1a46c0de3ad)
Comme il n'est pas supporté, c'est difficile à utiliser.

## Solutions 
- Forcer le théme blanc par défaut
- Adapter le théme noir du site

**Comment by Destinyyyy** [comment]
@juliendauphant-betagouv Ce problème a déjà été résolu, il faut que tu vides ton localStorage
https://mattermost.incubateur.net/betagouv/pl/1hbt8dyipj8gigpdm9pxsfsmzw
https://github.com/betagouv/pass-sport/pull/42

Tu peux re-tester et me dire si c'est bon?
